name: Infra Deploy - Staging

on:
  push:
    paths:
      - 'Infra/tfvars/staging/**'

jobs:
  terraform-staging:
    name: Apply Terraform - Staging
    runs-on: ubuntu-latest
    environment: staging-infra-approval

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.CREDENTIALS }}

      - name: Terraform Init
        working-directory: Infra/infrastructure
        run: terraform init

      - name: Terraform Plan
        working-directory: Infra/infrastructure
        run: terraform plan -var-file="../tfvars/staging/staging.tfvars"

      - name: Terraform Apply (manual approval required)
        working-directory: Infra/infrastructure
        run: terraform apply -var-file="../tfvars/staging/staging.tfvars"
